# Generated by Django 4.1.7 on 2023-04-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('specAn', models.CharField(max_length=255)),
                ('nameAnim', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('textArea', models.CharField(max_length=255)),
            ],
        ),
    ]
